### ISSUE TITLE
CMake warnings using cmake 3.0.2

### ISSUE THREAD

**Issue by cianwilson** [TerraFERMA/TerraFERMA#15]
1: When trying to get the buckettools library name for the config file (this should be improved anyway with a version file as well)...
CMake Warning (dev) at buckettools/cpp/CMakeLists.txt:94 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "buckettools_cpp".
  Use the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

2: Our test target is apparently not good...
CMake Warning (dev) at CMakeLists.txt:243 (add_custom_target):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.

**Comment by cianwilson** [comment]
Also note there is a MACOSX_RPATH warning on OSX 10.10, which also uses CMake 3.0.2.

**Comment by mspieg** [comment]
Correction macosx 10.10 is using cmake 3.3.0. But all new warnings come from cmake major version >=3

**Comment by cianwilson** [comment]
These should now be fixed:
1. by 2132ab0056fca73d7b48a66449d16e3a87746a70 which replaces our old crappy way of constructing the BUCKETTOOLSConfig.cmake file with the more CMakeish way of generating a BUCKETTOOLSTargets.cmake file which is then included in the config file to locate the library.  This change also includes version numbering (currently set to 0.9.0 until we tag 1.0.0) and streamlining of the loading of buckettools when building the terraferma executable.
2. by d30a8bdc35fa3687438c767fd5a94f6078a08710 which changes a lot of the target names to longer forms that CMake doesn't object to.  Most importantly `make test` is now `make run_shorttests`.  It also introduces similar targets for building and testing testable tutorials as well as building the manual.  These are mostly useful on buildbot and have been adopted there.  There is also a corresponding change to the run_tftests autogenerated script for dorsal that has already been pushed.  Similarly the wiki has been updated.
3.  by a772b863b2cfad8e7985ad04f58392261ae88c50 which simply disables the RPATH stuff.  My current understanding is that we can't really use this until we require a more recent version of CMake anyway.  Sounds like it might be worth looking into though.
